name: 'Random PR reviewers'
description:
  'Automatically assign random reviewers to Pull Requests and send a message to
  Google Chat Space'

branding:
  icon: 'user-plus'
  color: 'orange'

inputs:
  webhook-url:
    description: 'Google Chat webhook url'
    required: false
  repo-token:
    description: 'Github repository token secret'
    required: true
  reviewers:
    description: 'Number of reviewers'
    required: false
    default: 1
  usernames:
    description: 'List of Github usernames'
    required: true

runs:
  using: node20
  main: dist/index.js
